
export const MATCH_TICK_RATE = 10;
export const START_DELAY_SECONDS=20;
export const DICE_HUMAN_TIMEOUT_SECONDS=6;
export const DICE_BOT_TIMEOUT_SECONDS=2;
export const DICE_WAITING_FOR_ANIMATION=1;
export const ACTIONSELECT_HUMAN_TIMEOUT_SECONDS=6;
export const ACTIONSELECT_BOT_TIMEOUT_SECONDS=2;
export const END_MATCH_TIMEOUT_SECONDS=10;


